apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-configmap
  labels:
{{ include "portal.labels" . | indent 4 }}
data:
  env: |
    PORT={{ .Values.PORT }}

    DOMAIN={{ .Values.DOMAIN | quote }}
    LOGLEVEL={{ .Values.LOGLEVEL | quote }}
    DEVELOPMENT={{ .Values.DEVELOPMENT }}

    DATABASE_URI={{ .Values.DATABASE_URI | quote }}
    DATABASE_URI_RD={{ .Values.DATABASE_URI_RD | quote }}
    DATABASE_SCHEMA={{ .Values.DATABASE_SCHEMA | quote }}
    DATABASE_SYNCHRONIZE={{ .Values.DATABASE_SYNCHRONIZE }}
    DATABASE_DROP_SCHEMA={{ .Values.DATABASE_DROP_SCHEMA }}
    DATABASE_MIGRATIONS_RUN={{ .Values.DATABASE_MIGRATIONS_RUN }}
    DATABASE_LOGGING={{ .Values.DATABASE_LOGGING }}
    DATABASE_REDIS_URI={{ .Values.DATABASE_REDIS_URI | quote }}
    DATABASE_REDIS_TTL={{ .Values.DATABASE_REDIS_TTL }}

    # HTTP Redis
    HTTP_REDIS_URI={{ .Values.HTTP_REDIS_URI | quote }}
    HTTP_REDIS_TTL={{ .Values.HTTP_REDIS_TTL }}
    HTTP_REDIS_MAX_OBJECTS={{ .Values.HTTP_REDIS_MAX_OBJECTS }}

    # Session Redis
    SESSION_NAME={{ .Values.SESSION_NAME | quote }}
    SESSION_REDIS_URI={{ .Values.SESSION_REDIS_URI | quote }}
    SESSION_COOKIE_TTL={{ .Values.SESSION_COOKIE_TTL }}
    SESSION_SECRET={{ .Values.SESSION_SECRET | quote }}

    # LDAP
    LDAP_URL={{ .Values.LDAP_URL | quote }}
    LDAP_BIND_DN={{ .Values.LDAP_BIND_DN | quote }}
    LDAP_BIND_PW={{ .Values.LDAP_BIND_PW | quote }}
    LDAP_SEARCH_BASE={{ .Values.LDAP_SEARCH_BASE | quote }}
    LDAP_SEARCH_FILTER_ALL_USERS={{ .Values.LDAP_SEARCH_FILTER_ALL_USERS | quote }}
    LDAP_SEARCH_FILTER_ALL_GROUPS={{ .Values.LDAP_SEARCH_FILTER_ALL_GROUPS | quote }}
    LDAP_SEARCH_USER={{ .Values.LDAP_SEARCH_USER | quote }}
    LDAP_SEARCH_GROUP={{ .Values.LDAP_SEARCH_GROUP | quote }}
    LDAP_NEW_BASE={{ .Values.LDAP_NEW_BASE | quote }}
    LDAP_DOMAIN={{ .Values.LDAP_DOMAIN | quote }}
    # LDAP Redis
    LDAP_REDIS_URI={{ .Values.LDAP_REDIS_URI | quote }}
    LDAP_REDIS_TTL={{ .Values.LDAP_REDIS_TTL }}

    MICROSERVICE_URL={{ .Values.MICROSERVICE_URL | quote }}

    SOAP_URL={{ .Values.SOAP_URL | quote }}
    SOAP_DOMAIN={{ .Values.SOAP_DOMAIN | quote }}
    OSTICKET_URL={{ .Values.OSTICKET_URL }}

    NEXTCLOUD_URL={{ .Values.NEXTCLOUD_URL | quote }}
    NEXTCLOUD_REDIS_URI={{ .Values.NEXTCLOUD_REDIS_URI | quote }}
    NEXTCLOUD_REDIS_TTL={{ .Values.NEXTCLOUD_REDIS_TTL }}
    MAX_FILE_SIZE={{ .Values.MAX_FILE_SIZE }}

    NEWS_URL={{ .Values.NEWS_URL | quote }}
    NEWS_API_URL={{ .Values.NEWS_API_URL | quote }}

    MAIL_URL={{ .Values.MAIL_URL | quote }}
    MAIL_LOGIN_URL={{ .Values.MAIL_LOGIN_URL | quote }}

    MEETING_URL={{ .Values.MEETING_URL | quote }}
