apiVersion: v1
kind: Service
metadata:
  name: {{ include "portal.fullname" . }}
  labels:
{{ include "portal.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.PORT | default 4000 }}
      targetPort: {{ .Values.PORT | default 4000 }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
    - port: {{ .Values.PORT_DEBUGGER | default 9229 }}
      targetPort: {{ .Values.PORT_DEBUGGER | default 9229 }}
      {{- if .Values.service.nodePort_debugger }}
      nodePort: {{ .Values.service.nodePort_debugger }}
      {{- end }}
      protocol: TCP
      name: http-debugger
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "portal.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Values.image.tag }}
